#!/bin/bash
. /etc/node4ords.conf

#Check if node exists. Idea adapted from: http://stackoverflow.com/questions/592620/check-if-a-program-exists-from-a-bash-script
if hash node; then
    node ${APP_DIR}/${NODE_APP}
else
    echo "NodeJS doesn't exist on this system." >&2
    exit 1
fi
